/*******************************************************************************************************************************************************************
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
**********************************************************************************************************************************************************************/
class Solution {
public:
    char findTheDifference(string s, string t) {
        
        unordered_map<char,int>mp1;
        unordered_map<char,int>mp2;
        
        for(char&c1:s)
            mp1[c1]++;
        
        for(char&c2:t)
            mp2[c2]++;
        int i=0;
        int l1=s.size();
        int l2=t.size();
        while(l1-- || l2--)
        {
            if(mp1[t[i]]==0)
                return t[i];
            
            else
            {
                if(mp1[t[i]]!=mp2[t[i]])
                    return t[i];
            }
            i++;
            
        }
        return t[i];
      
      /*********************************************************************************************************************************************************/
      Idea;

All letters persent in s is present in t.
There is just one extra letter in t.
Every character can be represented as an ASCII .
ASCII value of the extra letter in t is derived as follows:
Sum of all ASCII values of charcters in s -> sSum
Sum of all ASCII values of charcters in t -> tSum
Return the difference (tSum-sSum)
Example 1:
s = 'abc'
t = 'abcd'
sSum = 97+98+99 = 294
tSum = 97+98+99+100 = 394

Example 2:
s = 'abc'
t = 'dbac'
sSum = 97+98+99 = 294
tSum = 100+98+97+99 = 394

In both examples, d (100) is the extra letter, which is equivalent to (tSum - sSum).

So the real question is:

Do we really need to store these in two variables? Or even in one other variable to maintain the diff?
Should we iterate through each of the strings separately?
Nope, here's the code:
  
  

class Solution {
public:
    char findTheDifference(string s, string t) 
    {
      for(int i=0;i<s.size();i++)
		t[i+1]+=t[i]-s[i]; //Passing the diff: (t[i]-s[i]) to t[i+1]
      return t[t.size()-1]; //The diff will be carried over to the last element eventually
    }
};
      
      
Instead of storing the diff at each point, passing it over to the next element would do the trick. We do this till the last element of t. Remember,
      t has one letter more than s always :)
Order of characters does not affect it as we are more focused on the difference of overall sum of ASCII of each letter in each arrray, s and t.
        
        
        
    }
};
